name: CI Tests

on:
  - push
  - pull_request

jobs:

  tests_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Install Go v1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Run CI Tests
        run: echo "Ran some CI Tests"